/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PUBLICRouteRouteImport } from './routes/(PUBLIC)/route'
import { Route as DASHBOARDRouteRouteImport } from './routes/(DASHBOARD)/route'
import { Route as AUTHRouteRouteImport } from './routes/(AUTH)/route'
import { Route as PUBLICIndexRouteImport } from './routes/(PUBLIC)/index'
import { Route as DASHBOARDDashboardOrganizationsRouteImport } from './routes/(DASHBOARD)/dashboard/organizations'
import { Route as AUTHAuthSignInRouteImport } from './routes/(AUTH)/auth/sign-in'
import { Route as DASHBOARDDashboardOrgOrgIdRouteImport } from './routes/(DASHBOARD)/dashboard/org/$orgId'

const PUBLICRouteRoute = PUBLICRouteRouteImport.update({
  id: '/(PUBLIC)',
  getParentRoute: () => rootRouteImport,
} as any)
const DASHBOARDRouteRoute = DASHBOARDRouteRouteImport.update({
  id: '/(DASHBOARD)',
  getParentRoute: () => rootRouteImport,
} as any)
const AUTHRouteRoute = AUTHRouteRouteImport.update({
  id: '/(AUTH)',
  getParentRoute: () => rootRouteImport,
} as any)
const PUBLICIndexRoute = PUBLICIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PUBLICRouteRoute,
} as any)
const DASHBOARDDashboardOrganizationsRoute =
  DASHBOARDDashboardOrganizationsRouteImport.update({
    id: '/dashboard/organizations',
    path: '/dashboard/organizations',
    getParentRoute: () => DASHBOARDRouteRoute,
  } as any)
const AUTHAuthSignInRoute = AUTHAuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => AUTHRouteRoute,
} as any)
const DASHBOARDDashboardOrgOrgIdRoute =
  DASHBOARDDashboardOrgOrgIdRouteImport.update({
    id: '/dashboard/org/$orgId',
    path: '/dashboard/org/$orgId',
    getParentRoute: () => DASHBOARDRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PUBLICIndexRoute
  '/auth/sign-in': typeof AUTHAuthSignInRoute
  '/dashboard/organizations': typeof DASHBOARDDashboardOrganizationsRoute
  '/dashboard/org/$orgId': typeof DASHBOARDDashboardOrgOrgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PUBLICIndexRoute
  '/auth/sign-in': typeof AUTHAuthSignInRoute
  '/dashboard/organizations': typeof DASHBOARDDashboardOrganizationsRoute
  '/dashboard/org/$orgId': typeof DASHBOARDDashboardOrgOrgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(AUTH)': typeof AUTHRouteRouteWithChildren
  '/(DASHBOARD)': typeof DASHBOARDRouteRouteWithChildren
  '/(PUBLIC)': typeof PUBLICRouteRouteWithChildren
  '/(PUBLIC)/': typeof PUBLICIndexRoute
  '/(AUTH)/auth/sign-in': typeof AUTHAuthSignInRoute
  '/(DASHBOARD)/dashboard/organizations': typeof DASHBOARDDashboardOrganizationsRoute
  '/(DASHBOARD)/dashboard/org/$orgId': typeof DASHBOARDDashboardOrgOrgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/dashboard/organizations'
    | '/dashboard/org/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/dashboard/organizations'
    | '/dashboard/org/$orgId'
  id:
    | '__root__'
    | '/(AUTH)'
    | '/(DASHBOARD)'
    | '/(PUBLIC)'
    | '/(PUBLIC)/'
    | '/(AUTH)/auth/sign-in'
    | '/(DASHBOARD)/dashboard/organizations'
    | '/(DASHBOARD)/dashboard/org/$orgId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AUTHRouteRoute: typeof AUTHRouteRouteWithChildren
  DASHBOARDRouteRoute: typeof DASHBOARDRouteRouteWithChildren
  PUBLICRouteRoute: typeof PUBLICRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(PUBLIC)': {
      id: '/(PUBLIC)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PUBLICRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(DASHBOARD)': {
      id: '/(DASHBOARD)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DASHBOARDRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(AUTH)': {
      id: '/(AUTH)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AUTHRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(PUBLIC)/': {
      id: '/(PUBLIC)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PUBLICIndexRouteImport
      parentRoute: typeof PUBLICRouteRoute
    }
    '/(DASHBOARD)/dashboard/organizations': {
      id: '/(DASHBOARD)/dashboard/organizations'
      path: '/dashboard/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DASHBOARDDashboardOrganizationsRouteImport
      parentRoute: typeof DASHBOARDRouteRoute
    }
    '/(AUTH)/auth/sign-in': {
      id: '/(AUTH)/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AUTHAuthSignInRouteImport
      parentRoute: typeof AUTHRouteRoute
    }
    '/(DASHBOARD)/dashboard/org/$orgId': {
      id: '/(DASHBOARD)/dashboard/org/$orgId'
      path: '/dashboard/org/$orgId'
      fullPath: '/dashboard/org/$orgId'
      preLoaderRoute: typeof DASHBOARDDashboardOrgOrgIdRouteImport
      parentRoute: typeof DASHBOARDRouteRoute
    }
  }
}

interface AUTHRouteRouteChildren {
  AUTHAuthSignInRoute: typeof AUTHAuthSignInRoute
}

const AUTHRouteRouteChildren: AUTHRouteRouteChildren = {
  AUTHAuthSignInRoute: AUTHAuthSignInRoute,
}

const AUTHRouteRouteWithChildren = AUTHRouteRoute._addFileChildren(
  AUTHRouteRouteChildren,
)

interface DASHBOARDRouteRouteChildren {
  DASHBOARDDashboardOrganizationsRoute: typeof DASHBOARDDashboardOrganizationsRoute
  DASHBOARDDashboardOrgOrgIdRoute: typeof DASHBOARDDashboardOrgOrgIdRoute
}

const DASHBOARDRouteRouteChildren: DASHBOARDRouteRouteChildren = {
  DASHBOARDDashboardOrganizationsRoute: DASHBOARDDashboardOrganizationsRoute,
  DASHBOARDDashboardOrgOrgIdRoute: DASHBOARDDashboardOrgOrgIdRoute,
}

const DASHBOARDRouteRouteWithChildren = DASHBOARDRouteRoute._addFileChildren(
  DASHBOARDRouteRouteChildren,
)

interface PUBLICRouteRouteChildren {
  PUBLICIndexRoute: typeof PUBLICIndexRoute
}

const PUBLICRouteRouteChildren: PUBLICRouteRouteChildren = {
  PUBLICIndexRoute: PUBLICIndexRoute,
}

const PUBLICRouteRouteWithChildren = PUBLICRouteRoute._addFileChildren(
  PUBLICRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AUTHRouteRoute: AUTHRouteRouteWithChildren,
  DASHBOARDRouteRoute: DASHBOARDRouteRouteWithChildren,
  PUBLICRouteRoute: PUBLICRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
